version: '3.8'

services:
  #tell to build using dockerfile
  phresh_new_arc_api:
    container_name: phresh_ddd_arc_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    #save the backend files to volume (More later)
    volumes:
      - ./backend/:/backend/
    #all other environment variables taken from .env file
    env_file:
      - ./backend/.envs/.local.env
    ports:
      - 8000:8000
    command: ./scripts/run-dev.sh
    depends_on:
      - postgres

  #added new service called db and pull down the postgres-13-alpine image
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.envs/.local.env
    ports:
      - 5432:5432

# volume assure that our containers can maintain state between runs
# We wouldn't want to drop our database each time we kill our running container.
volumes:
  postgres_data: {}
